version: 2

models:
  - name: fato_acidente_trabalho
    description: "Tabela fato contendo as ocorrências de acidentes de trabalho"
    columns:
      - name: id_acidente
        description: "Chave substituta determinística"
        tests:
          - not_null
          - unique

      - name: dt_acid
        description: "Data do acidente"
        tests:
          - not_null
          - relationships:
              to: ref('dim_tempo')
              field: data_evento

      - name: cs_sexo
        description: "Código do sexo"
        tests:
          - relationships:
              to: ref('dim_sexo')
              field: codigo

      - name: cs_raca
        description: "Código de raça/cor"
        tests:
          - relationships:
              to: ref('dim_raca')
              field: codigo

      - name: tipo_acid
        description: "Código do tipo de acidente"
        tests:
          - relationships:
              to: ref('dim_tipo_acidente')
              field: codigo

      - name: part_corp1
        description: "Parte do corpo 1"
        tests:
          - relationships:
              to: ref('dim_partes_corpo')
              field: codigo

      - name: part_corp2
        description: "Parte do corpo 2"
        tests:
          - relationships:
              to: ref('dim_partes_corpo')
              field: codigo

      - name: part_corp3
        description: "Parte do corpo 3"
        tests:
          - relationships:
              to: ref('dim_partes_corpo')
              field: codigo

      - name: evolucao
        description: "Código da evolução do caso"
        tests:
          - relationships:
              to: ref('dim_evolucao')
              field: codigo

      - name: sg_uf
        description: "UF do acidente"
        tests:
          - accepted_values:
              values: ["AC","AL","AP","AM","BA","CE","DF","ES","GO","MA","MT","MS","MG","PA","PB","PR","PE","PI","RJ","RN","RS","RO","RR","SC","SP","SE","TO"]
          - relationships:
              to: ref('dim_localidade')
              field: uf
