version: 2

sources:
  - name: raw
    database: ACIDENTES_DB
    schema: RAW
    tables:
      - name: acidentes_trabalho_raw
        description: "Tabela bruta carregada via COPY INTO (stage interno)."
        loaded_at_field: dt_notific   # ou dt_acid, se preferir
        freshness:
          warn_after: {count: 365, period: day}
          error_after: {count: 730, period: day}

sources:
  - name: raw
    database: ACIDENTES_DB
    schema: RAW
    tables:
      - name: acidentes_trabalho_raw
        description: "Carga bruta do SINAN (acidente de trabalho)."
        freshness:
          warn_after: {count: 30, period: day}
          error_after: {count: 90, period: day}