version: 2

sources:
  - name: raw
    database: ACIDENTES_DB
    schema: RAW
    tables:
      - name: acidentes_trabalho_raw
        description: "Base bruta do SINAN – Acidente de Trabalho (ACGRBR24)"
        columns:
          - name: TP_NOT
            description: "Tipo de notificação"
          - name: ID_AGRAVO
            description: "Código do agravo (CID-10) notificado"
          - name: DT_NOTIFIC
            description: "Data da notificação"
          - name: DT_ACID
            description: "Data do acidente"
          - name: CID_LESAO
            description: "CID-10 do diagnóstico da lesão"
          - name: CID_ACID
            description: "CID-10 da causa externa do acidente (V01–Y98)"
          - name: CS_SEXO
            description: "Sexo do paciente (M/F/I)"
          - name: CS_RACA
            description: "Raça/Cor (1-branca,2-preta,3-amarela,4-parda,5-indígena,9-ignorado)"
          - name: TIPO_ACID
            description: "Tipo de acidente (1-Típico, 2-Trajeto, 9-Ignorado)"
          - name: PART_CORP1
            description: "Parte do corpo atingida 1"
          - name: PART_CORP2
            description: "Parte do corpo atingida 2"
          - name: PART_CORP3
            description: "Parte do corpo atingida 3"
          - name: EVOLUCAO
            description: "Evolução do caso"
          - name: CAT
            description: "Foi emitida CAT (1-Sim,2-Não,3-Não se aplica,9-Ignorado)"
          - name: NU_TRAB
            description: "Quantidade de trabalhadores atingidos no evento"
          - name: SG_UF
            description: "UF de residência"
          - name: SG_UF_NOT
            description: "UF da notificação"
          - name: MUN_ACID
            description: "Município de ocorrência do acidente (IBGE)"
